---
- name: Deploy Docker Compose traefik
  hosts: ubuntu-docker
  vars_files:
    - credentials.yml
  become: true
  tasks:
    - name: Update system
      command: apt update

    - name: Ensure docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure docker-compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Ensure rsync is installed
      apt:
        name: rsync
        state: present

    - name: Supprimer le dossier grafana avant copie
      file:
        path: "/home/{{ ansible_ssh_user }}/traefik-host/grafana"
        state: absent

    - name: Copying app in ubuntu-docker
      become: false
      synchronize:
        src: ./app/
        dest: "/home/{{ ansible_ssh_user }}/traefik-host"
        rsync_opts:
          - "--delete"
          - "--exclude=certificates/acme.json"
          - "--exclude=certificates/acme-home.json"
          # - "--chown=thibaut:thibaut"

    - name: Fix permissions on Grafana data folder
      file:
        path: "/home/{{ ansible_ssh_user }}/traefik-host/grafana"
        owner: 472
        group: 472
        mode: '0755'
        recurse: yes

    - name: Check if certificates/acme.json exists and is not empty
      become: false
      stat:
        path: "/home/{{ ansible_ssh_user }}/traefik-host/certificates/acme.json"
      register: acme_file

    - name: Check if certificates/acme-home.json exists and is not empty
      become: false
      stat:
        path: "/home/{{ ansible_ssh_user }}/traefik-host/certificates/acme-home.json"
      register: acme_home

    - name: Synchronize certificates/acme.json if it doesn't exist or is empty
      become: false
      synchronize:
        src: ./app/certificates/acme.json
        dest: "/home/{{ ansible_ssh_user }}/traefik-host/certificates/acme.json"
      when: not acme_file.stat.exists or acme_file.stat.size == 0

    - name: Synchronize certificates/acme-home.json if it doesn't exist or is empty
      become: false
      synchronize:
        src: ./app/certificates/acme-home.json
        dest: "/home/{{ ansible_ssh_user }}/traefik-host/certificates/acme-home.json"
      when: not acme_home.stat.exists or acme_home.stat.size == 0

    # - name: Set permissions to 600 for acme-home.json if it was just created
    #   file:
    #     path: "/home/{{ ansible_ssh_user }}/traefik-host/certificates/acme-home.json"
    #     mode: '0600'
    #   when: not acme_home.stat.exists

    # - name: Set permissions to 600 for acme.json if it was just created
    #   file:
    #     path: "/home/{{ ansible_ssh_user }}/traefik-host/certificates/acme.json"
    #     mode: '0600'
    #   when: not acme_file.stat.exists

    - name: Stop docker-compose for app
      docker_compose:
        project_src: '/home/{{ ansible_ssh_user }}/traefik-host'
        state: absent
        remove_orphans: yes

    - name: Attente 10s pour arrêt complet
      pause:
        seconds: 10

    - name: Start docker-compose for app
      docker_compose:
        project_src: '/home/{{ ansible_ssh_user }}/traefik-host'
        state: present
