---
- name: Deploy Docker Compose project
  hosts: ubuntu-docker
  become: true
  tasks:
    - name: Update system
      command: apt update

    - name: Ensure docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure docker-compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Ensure rsync is installed
      apt:
        name: rsync
        state: present

    - name: Copying app in ubuntu-docker
      become: false
      synchronize:
        src: ./app/
        dest: "/home/{{ ansible_ssh_user }}/traefik-host"
        rsync_opts:
          - "--exclude=certificates/acme.json"

    - name: Check if certificates/acme.json exists and is not empty
      become: false
      stat:
        path: "/home/{{ ansible_ssh_user }}/traefik-host/certificates/acme.json"
      register: acme_file

    - name: Synchronize certificates/acme.json if it doesn't exist or is empty
      become: false
      synchronize:
        src: ./app/certificates/acme.json
        dest: "/home/{{ ansible_ssh_user }}/traefik-host/certificates/acme.json"
      when: not acme_file.stat.exists or acme_file.stat.size == 0

    - name: Set permissions to 600 for acme.json if it was just created
      file:
        path: "/home/{{ ansible_ssh_user }}/traefik-host/certificates/acme.json"
        mode: '0600'
      when: not acme_file.stat.exists

    - name: Copying ddns in ubuntu-docker
      become: false
      synchronize:
        src: ./ddns/
        dest: "/home/{{ ansible_ssh_user }}/ddns-host"

    - name: Execute ddns startup script
      command: bash /home/{{ ansible_ssh_user }}/ddns-host/conf/startup.sh

    - name: Change owner of ddns/conf/data directory
      file:
        path: /home/{{ ansible_ssh_user }}/ddns-host/conf/data
        owner: 1000
        recurse: yes

    - name: Update permissions of ddns/conf/data directory
      file:
        path: /home/{{ ansible_ssh_user }}/ddns-host/conf/data
        mode: '0777'

    - name: Update permissions of ddns/conf/data/config.json file
      file:
        path: /home/{{ ansible_ssh_user }}/ddns-host/conf/data/config.json
        mode: '0777'

    - name: Stop docker-compose for ddns
      docker_compose:
        project_src: '/home/{{ ansible_ssh_user }}/ddns-host'
        state: absent

    - name: Start docker-compose for ddns
      docker_compose:
        project_src: '/home/{{ ansible_ssh_user }}/ddns-host'
        state: present

    - name: Stop docker-compose for app
      docker_compose:
        project_src: '/home/{{ ansible_ssh_user }}/traefik-host'
        state: absent

    - name: Start docker-compose for app
      docker_compose:
        project_src: '/home/{{ ansible_ssh_user }}/traefik-host'
        state: present
