http:
  routers:
    nextcloud:
      rule: "Host(`nextcloud.thibaut-husser.com`) || Host(`www.nextcloud.thibaut-husser.com`) || Host(`nextcloud.thusser.com`) || Host(`www.nextcloud.thusser.com`)"
      entryPoints:
        - websecure
      service: nextcloud_service
      tls:
        certResolver: letsencrypt-flare
      middlewares:
        - "nextcloud-headers"
        - "nextcloud-dav"
        - "redirect-to-https-nextcloud"
        - "secure-headers"

  services:
    nextcloud_service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.84:9001"

  middlewares:
    redirect-to-https-nextcloud:
      redirectScheme:
        scheme: https
        permanent: true
    nextcloud-dav:
      replacePathRegex:
        regex: "^/.well-known/ca(l|rd)dav"
        replacement: "/remote.php/dav/"
    nextcloud-headers:
      headers:
        # cookie:
        #   secure: true
        #   samesite: "None"
        customFrameOptionsValue: "SAMEORIGIN"
        forceSTSHeader: true
        frameDeny: true  # Attention a re mettre si header de websockets !
        # stsSeconds: 15552000
        # stsIncludeSubdomains: true
        # stsPreload: true
        # browserXssFilter: true
