http:
  routers:
    proxmox:
      rule: "Host(`proxmox.thibaut-husser.com`) || Host(`www.proxmox.thibaut-husser.com`) || Host(`proxmox.thusser.com`) || Host(`www.proxmox.thusser.com`)"
      entryPoints:
        - websecure
      service: proxmox_service
      tls:
        certresolver: letsencrypt-flare
      middlewares:
        - headers-proxmox
        - compress
        - websocket
        - secure-headers

  services:
    proxmox_service:
      loadBalancer:
        servers:
          - url: "https://192.168.1.78:8006"
        serversTransport: "pve"

  serversTransports:
    pve:
      insecureSkipVerify: true

  middlewares:
    headers-proxmox:
      headers:
        customRequestHeaders:
          Host: "proxmox.thibaut-husser.com"
        contentTypeNosniff: true

