http:
  routers:
    truenas:
      rule: "Host(`nas.thibaut-husser.com`, `www.nas.thibaut-husser.com`)"
      entryPoints:
        - websecure
      service: truenas_service
      tls:
        certresolver: letsencrypt-flare
      middlewares:
        - headers-truenas
        - compress-truenas
        - websocket-truenas

  services:
    truenas_service:
      loadBalancer:
        servers:
          - url: "https://192.168.1.84"
        serversTransport: "webUiTruenas"

  serversTransports:
    webUiTruenas:
      insecureSkipVerify: true

  middlewares:
    headers-truenas:
      headers:
        customRequestHeaders:
          Host: "nas.thibaut-husser.com"
        contentTypeNosniff: true
        browserXssFilter: true

    compress-truenas:
      compress: {}

    websocket-truenas:
      headers:
        customRequestHeaders:
          Connection: Upgrade
          Upgrade: WebSocket

