http:
  routers:
    vaultwarden:
      rule: "Host(`bitwarden.thibaut-husser.com`) || Host(`www.bitwarden.thibaut-husser.com`)"
      entryPoints:
        - websecure
      service: vaultwarden_service
      tls:
        certresolver: letsencrypt-flare
      middlewares:
        - add-xss-header
        - headers-vaultwarden
        - compress
        - websocket
        - secure-headers

  services:
    vaultwarden_service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.93:80"

  middlewares:
    headers-vaultwarden:
      headers:
        customRequestHeaders:
          Host: "bitwarden.thibaut-husser.com"
        contentTypeNosniff: true
    
    add-xss-header:
      headers:
        customResponseHeaders:
          X-XSS-Protection: "0"
