http:
  routers:
    vaultwarden:
      rule: "Host(`bitwarden.thibaut-husser.com`, `www.bitwarden.thibaut-husser.com`)"
      entryPoints:
        - websecure
      service: vaultwarden_service
      tls:
        certresolver: letsencrypt-flare
      middlewares:
        - headers-vaultwarden
        - compress-vaultwarden
        - websocket-vaultwarden

  services:
    vaultwarden_service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.93:80"

  middlewares:
    headers-vaultwarden:
      headers:
        customRequestHeaders:
          Host: "bitwarden.thibaut-husser.com"
        contentTypeNosniff: true
        browserXssFilter: true

    compress-vaultwarden:
      compress: {}

    websocket-vaultwarden:
      headers:
        customRequestHeaders:
          Connection: Upgrade
          Upgrade: WebSocket
