http:
  routers:
    vpn:
      rule: "Host(`vpn.thibaut-husser.com`, `www.vpn.thibaut-husser.com`)"
      entryPoints:
        - websecure
      service: vpn_service
      tls:
        certresolver: letsencrypt-flare
      middlewares:
        - headers-vpn
        - compress-vpn

  services:
    vpn_service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.93:51821"

  middlewares:
    headers-vpn:
      headers:
        customRequestHeaders:
          Host: "vpn.thibaut-husser.com"
        contentTypeNosniff: true
        browserXssFilter: true

    compress-vpn:
      compress: {}
