http:
  routers:
    vpn:
      rule: "Host(`vpn.thibaut-husser.com`) || Host(`www.vpn.thibaut-husser.com`) || Host(`vpn.thusser.com`) || Host(`www.vpn.thusser.com`)"
      entryPoints:
        - websecure
      service: vpn_service
      tls:
        certresolver: letsencrypt-flare
      middlewares:
        - headers-vpn
        - compress
        - secure-headers

  services:
    vpn_service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.93:51821"

  middlewares:
    headers-vpn:
      headers:
        customRequestHeaders:
          Host: "vpn.thibaut-husser.com"
        contentTypeNosniff: true
