version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    restart: unless-stopped
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certificates/acme.json:/certificates/acme.json:rw"
      - "./certificates/acme-home.json:/certificates/acme-home.json:rw"
      - "./traefik-config:/etc/traefik"
      - "./log/traefik-service.log:/var/log/traefik/traefik-service.log"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_TOKEN}
    command:
      - "--log.filePath=/var/log/traefik/traefik-service.log"
      - "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--certificatesresolvers.letsencrypt-flare.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt-flare.acme.storage=/certificates/acme.json"
      - "--certificatesresolvers.letsencrypt-flare.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.delayBeforeCheck=0"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.letsencrypt-home.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt-home.acme.storage=/certificates/acme-home.json"
      - "--certificatesresolvers.letsencrypt-home.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt-home.acme.httpChallenge.entrypoint=web"
    labels:
        # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.thibaut-husser.com`, `www.traefik.thibaut-husser.com`)"
      - "traefik.http.routers.dashboard.entrypoints=web, websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${AUTH_USER}"

      ## Gestion domaine principale - Desactivation
      - "traefik.http.routers.main-domain.rule=Host(`thibaut-husser.com`)"
      - "traefik.http.routers.main-domain.entrypoints=web,websecure"
      - "traefik.http.routers.main-domain.tls=false"
      - "traefik.http.routers.main-domain.service=noop@internal"

  nginx-cv:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-cv"
    volumes:
      - ./nginx/cv:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-cv.rule=Host(`cv.thibaut-husser.com`, `www.cv.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-cv.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-cv.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.routers.nginx-cv.middlewares=nginx-redirect-to-https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"

