version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    restart: unless-stopped
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certificates/acme.json:/certificates/acme.json:rw"
      - "./certificates/acme-home.json:/certificates/acme-home.json:rw"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_TOKEN}
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt-flare.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt-flare.acme.storage=/certificates/acme.json"
      - "--certificatesresolvers.letsencrypt-flare.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.delayBeforeCheck=0"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.letsencrypt-home.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt-home.acme.storage=/certificates/acme-home.json"
      - "--certificatesresolvers.letsencrypt-home.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt-home.acme.httpChallenge.entrypoint=web"
    labels:
      - "traefik.http.middlewares.hstsheaders.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.hstsheaders.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.hstsheaders.headers.stsPreload=true"
        # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.thibaut-husser.com`, `www.traefik.thibaut-husser.com`)"
      - "traefik.http.routers.dashboard.entrypoints=web, websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${AUTH_USER}"
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.frontend.redirect.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav"

  nginx-nas:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-nas"
    volumes:
      - ./nginx/nginx-nas.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-nas.rule=Host(`nas.thibaut-husser.com`, `www.nas.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-nas.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-nas.tls.certresolver=letsencrypt-flare"

  nginx-proxmox:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-proxmox"
    volumes:
      - ./nginx/nginx-proxmox.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-proxy.rule=Host(`proxmox.thibaut-husser.com`, `www.proxmox.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-proxy.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-proxy.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.routers.nginx-proxy.middlewares=nginx-redirect-to-https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"

  nginx-cv:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-cv"
    volumes:
      - ./nginx/cv:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-cv.rule=Host(`cv.thibaut-husser.com`, `www.cv.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-cv.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-cv.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.routers.nginx-cv.middlewares=nginx-redirect-to-https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"

  nginx-synapse:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-synapse"
    volumes:
      - ./nginx/nginx-synapse.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-synapse.rule=Host(`matrix.thibaut-husser.com`, `www.matrix.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-synapse.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-synapse.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.routers.nginx-synapse.middlewares=nginx-redirect-to-https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"

  nginx-portainer:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-portainer"
    volumes:
      - ./nginx/nginx-portainer.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-portainer.rule=Host(`portainer.thibaut-husser.com`, `www.portainer.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-portainer.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-portainer.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.routers.nginx-portainer.middlewares=nginx-redirect-to-https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"

  nginx-nextcloud:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-nextcloud"
    volumes:
      - ./nginx/nginx-nextcloud.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-nextcloud.rule=Host(`nextcloud.thibaut-husser.com`, `www.nextcloud.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-nextcloud.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-nextcloud.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.routers.nginx-nextcloud.middlewares=nginx-redirect-to-https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.nginx-nextcloud.middlewares=hstsheaders@docker,nextcloud-dav"
      # - "traefik.http.routers.nextcloud.middlewares=nextcloud_redirectregex"
      # - "traefik.http.nextcloud.middlewares.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"

  nginx-vaultwarden:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-vaultwarden"
    volumes:
      - ./nginx/nginx-vaultwarden.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-vaultwarden.rule=Host(`bitwarden.thibaut-husser.com`, `www.bitwarden.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-vaultwarden.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-vaultwarden.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.routers.nginx-vaultwarden.middlewares=nginx-redirect-to-https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"
