services:
  traefik:
    image: "traefik:3.3.4"
    restart: unless-stopped
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certificates/acme.json:/certificates/acme.json:rw"
      - "./certificates/acme-home.json:/certificates/acme-home.json:rw"
      - "./traefik-config:/etc/traefik"
      - "./log/traefik-service.log:/var/log/traefik/traefik-service.log"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_TOKEN}
    command:
      # - "--entrypoints.websecure.forwardedHeaders.trustedIPs=192.168.1.0/24,172.16.0.0/12,127.0.0.1/32"
      # - "--entrypoints.websecure.forwardedHeaders.insecure=true"
      # - "--entrypoints.web.forwardedHeaders.insecure=true"
      - "--log.filePath=/var/log/traefik/traefik-service.log"
      - "--log.level=debug"
      - "--api=true"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      # - "--configFile=/etc/traefik/traefik.yml"
      - "--certificatesresolvers.letsencrypt-flare.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt-flare.acme.storage=/certificates/acme.json"
      - "--certificatesresolvers.letsencrypt-flare.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.delayBeforeCheck=0"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      # - "--certificatesresolvers.letsencrypt-home.acme.email=${ACME_EMAIL}"
      # - "--certificatesresolvers.letsencrypt-home.acme.storage=/certificates/acme-home.json"
      # - "--certificatesresolvers.letsencrypt-home.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.letsencrypt-home.acme.httpChallenge.entrypoint=web"
    labels:
        # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.thibaut-husser.com`) || Host(`www.traefik.thibaut-husser.com`)"
      - "traefik.http.routers.dashboard.entrypoints=web, websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.dashboard.middlewares=local-only@file,auth"
      - "traefik.http.middlewares.auth.basicauth.users=${AUTH_USER}"

      ## Gestion domaine principale - Desactivation
      # - "traefik.http.routers.main-domain.rule=Host(`thibaut-husser.com`)"
      # - "traefik.http.routers.main-domain.entrypoints=web,websecure"
      # - "traefik.http.routers.main-domain.tls=false"
      # - "traefik.http.routers.main-domain.service=noop@internal"

      ## Homeassistant test labels
      # - "traefik.http.routers.homeassistant.rule=Host(`ha.thibaut-husser.com`)"
      # - "traefik.http.routers.homeassistant.entrypoints=https"
      # - "traefik.http.routers.homeassistant.tls=true"
      # # - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      # - "traefik.http.services.homeassistant.loadbalancer.servers.url=http://192.168.1.48:8123"
      # - "traefik.http.routers.homeassistant.middlewares=hstsHeader"
      # - "traefik.http.middlewares.hstsHeader.headers.stsSeconds=15552000"
      # - "traefik.http.middlewares.hstsHeader.headers.stsIncludeSubdomains=true"
      # - "traefik.http.middlewares.hstsHeader.headers.stsPreload=true"
      # - "traefik.http.routers.traefik.middlewares=hstsHeader"

  nginx-cv:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-cv"
    volumes:
      - ./nginx/cv:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-cv.rule=Host(`cv.thibaut-husser.com`) || Host(`www.cv.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-cv.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-cv.tls.certresolver=letsencrypt-flare"
      # - "traefik.http.routers.nginx-cv.middlewares=nginx-redirect-to-https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    volumes:
      - ./homer:/www/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`thibaut-husser.com`)"
      - "traefik.http.routers.homer.entrypoints=websecure"
      - "traefik.http.routers.homer.tls.certresolver=letsencrypt-flare"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
      - "traefik.http.routers.homer.middlewares=redirect-plex@file,redirect-nas@file,local-only@file,secure-headers@file,compress@file,force-real-ip@file"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - traefik

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    user: "472:472"

