version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    restart: unless-stopped
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certificates/acme.json:/certificates/acme.json:rw"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt-flare.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt-flare.acme.storage=/certificates/acme.json"
      - "--certificatesresolvers.letsencrypt-flare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.delayBeforeCheck=0"
      - "--certificatesresolvers.letsencrypt-flare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
    labels:
        # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.thibaut-husser.com`)"
      - "traefik.http.routers.dashboard.entrypoints=web, websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt-flare"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${AUTH_USER}"

  nginx-nas:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-nas"
    volumes:
      - ./nginx/nginx-nas.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-nas.rule=Host(`nas.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-nas.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-nas.tls.certresolver=letsencrypt-flare"
      - "traefik.http.routers.nginx-nas.middlewares=nginx-redirect-to-https"
      - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"

  nginx-proxmox:
    image: nginx:1.25.2
    restart: unless-stopped
    container_name: "nginx-proxmox"
    volumes:
      - ./nginx/nginx-proxmox.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-proxy.rule=Host(`proxmox.thibaut-husser.com`)"
      - "traefik.http.routers.nginx-proxy.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-proxy.tls.certresolver=letsencrypt-flare"
      - "traefik.http.routers.nginx-proxy.middlewares=nginx-redirect-to-https"
      - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.nginx-redirect-to-https.redirectscheme.permanent=true"

